name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Aula15)
        run: python -m pip install --upgrade pip && pip install -r Aula15/requirements.txt

      - name: Run tests (Aula15)
        run: pytest
        working-directory: Aula15

      - name: Install dependencies (Aula16)
        run: python -m pip install --upgrade pip && pip install -r Aula16/requirements.txt

      - name: Run tests (Aula16)
        run: pytest
        working-directory: Aula16
